version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # สำหรับ S3 API
      - "9001:9001"     # สำหรับ Web UI
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin         # username
      MINIO_ROOT_PASSWORD: minioadmin     # password
    command: server /data --console-address ":9001"

  kafka:
    image: docker.io/bitnami/kafka:4.0
    container_name: kafka
    ports:
      - "9092:9092"      # สำหรับ Go ภายนอก
      - "29092:29092"    # สำหรับ container ภายใน (KafkaUI)
    volumes:
      - kafka_data:/bitnami
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafkaui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

volumes:
  minio-data:
  kafka_data:
