services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # สำหรับ S3 API
      - "9001:9001"     # สำหรับ Web UI
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin         # username
      MINIO_ROOT_PASSWORD: minioadmin     # password
    command: server /data --console-address ":9001"

volumes:
  minio-data: